=== hblanko/cookbase/resources/schemas/recipe.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://cercadevigo.ddns.net:8080/schemas/recipe.json",
  "type": "object",
  "properties": {
    "_id" : {
      "bsonType": "objectId"
    },
    "info": {
      "$ref": "info.json"
    },
    "yield": {
      "$ref": "yield.json"
    },
    "ingredients": {
      "type": "object",
      "patternProperties": {
        "^part[1-9]\\d{0,1}$": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "additionalProperties": {
              "$ref": "ingredient.json"
            }
          }
        }
      },
      "additionalProperties": false
    },
    "instruments": {
      "type": "object",
      "patternProperties": {
        "^inst[1-9]\\d{0,1}$": {
          "$ref": "instrument.json"
        }
      },
      "additionalProperties": false
    },
    "preparation": {
      "type": "object",
      "patternProperties": {
        "^proc[1-9]\\d{0,1}$": {
          "$ref": "process.json"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "info",
    "yield",
    "ingredients",
    "instruments",
    "preparation"
  ],
  "additionalProperties": false
}

=== hblanko/cookbase/cookbase/tests/resources/wrongPizzaMozzarella.json
{
  "info": {
    "name": "Pizza mozzarella",
    "authorship": {
      "fullName": "Hernán Blanco",
      "version": "0.1"
    },
    "releaseDate": "2019-09-01",
    "cuisine": [
      "Argentine"
    ],
    "courseType": [
      "main dish"
    ],
    "preparationTime": {
      "value": 105,
      "measure": "min"
    },
    "cookingTime": {
      "value": 17,
      "measure": "min"
    },
    "servingTime": {
      "value": 1,
      "measure": "min"
    }
  },
  "yield": {
    "servings": 8,
    "servingSize": {
      "descriptive": "medium",
      "weight": {
        "value": 160,
        "measure": "g"
      },
      "volume": {
        "value": 400,
        "measure": "ml"
      }
    },
    "servingFormat": "dinner plate"
  },
  "ingredients": {
    "part1": {
      "name": "dough",
      "ing1": {
        "name": "strong wheat flour",
        "amount": {
          "value": 350,
          "measure": "g"
        }
      },
      "ing2": {
        "name": "water",
        "amount": {
          "value": 200,
          "measure": "g"
        }
      },
      "ing3": {
        "name": "sugar",
        "amount": {
          "value": 7,
          "measure": "g"
        }
      },
      "ing4": {
        "name": "yeast",
        "amount": {
          "value": 21,
          "measure": "g"
        }
      },
      "ing5": {
        "name": "olive oil",
        "amount": {
          "value": 8,
          "measure": "g"
        }
      },
      "ing6": {
        "name": "salt",
        "amount": {
          "value": 8,
          "measure": "g"
        }
      }
    },
    "part2": {
      "name": "sauce",
      "ing7": {
        "name": "tomato sauce",
        "amount": {
          "value": 230,
          "measure": "g"
        }
      },
      "ing8": {
        "name": "garlic",
        "amount": {
          "value": 5,
          "measure": "g"
        }
      },
      "ing9": {
        "name": "olive oil",
        "amount": {
          "value": 6,
          "measure": "g"
        }
      },
      "ing10": {
        "name": "oregano",
        "amount": {
          "value": 2,
          "measure": "g"
        }
      },
      "ing11": {
        "name": "salt",
        "amount": {
          "value": 1,
          "measure": "g"
        }
      }
    },
    "part3": {
      "name": "topping",
      "ing12": {
        "type": {
          "k1": "cheese",
          "k2": "100%cow"
        },
        "name": "low moisture mozzarella",
        "amount": {
          "value": 550,
          "measure": "g"
        }
      },
      "ing13": {
        "name": "green olives",
        "optional": true
      },
      "ing14": {
        "name": "oregano",
        "optional": true
      }
    }
  },
  "instruments": {
    "inst1": {
      "family": "container",
      "type": "bowl",
      "properties": {
        "capacity": {
          "value": 0.3,
          "measure": "l"
        }
      }
    },
    "inst2": {
      "family": "container",
      "type": "bowl",
      "properties": {
        "capacity": {
          "value": 0.5,
          "measure": "l"
        }
      }
    },
    "inst3": {
      "family": "container",
      "type": "bowl",
      "properties": {
        "capacity": {
          "value": 1,
          "measure": "l"
        }
      }
    },
    "inst4": {
      "family": "container",
      "type": "bowl",
      "properties": {
        "capacity": {
          "value": 2,
          "measure": "l"
        }
      }
    },
    "inst5": {
      "family": "scoop",
      "type": "cooking spoon"
    },
    "inst6": {
      "type": "cutting board"
    },
    "inst7": {
      "family": "cutter",
      "type": "kitchen knife"
    },
    "inst8": {
      "type": "dough scraper",
      "optional": true
    },
    "inst9": {
      "family": "baking",
      "type": "pizza tray",
      "properties": {
        "diameter": {
          "value": 32,
          "measure": "cm"
        }
      }
    },
    "inst10": {
      "family": "oven",
      "type": "domestic oven",
      "properties": {
        "temperatureRange": {
          "maxTemperature": {
            "value": 250,
            "measure": "°C"
          }
        }
      }
    },
    "inst11": {
      "type": "oven glove"
    },
    "inst12": {
      "family": "stirrer",
      "properties": {
        "size": {
          "relativeTo": "inst1"
        }
      }
    },
    "inst13": {
      "type": "kitchen scale"
    },
    "inst14": {
      "family": "surface",
      "type": "worktop"
    },
    "inst15": {
      "family": "plate",
      "type": "dinner plate",
      "properties": {
        "diameter": {
          "value": 32,
          "measure": "cm"
        }
      }
    },
    "inst16": {
      "family": "serving",
      "type": "spatula"
    }
  },
  "preparation": {
    "proc1": {
      "process": "adding ingredients",
      "foodstuffsList": [
        "ing2",
        "ing3",
        "ing4"
      ],
      "instruments": [
        {
          "instrument": "inst1",
          "usedAfter": true
        }
      ]
    },
    "proc2": {
      "process": "mixing",
      "foodstuff": "proc1",
      "instruments": [
        {
          "instrument": "inst1",
          "usedAfter": true
        },
        {
          "instrument": "inst12",
          "usedAfter": false
        }
      ]
    },
    "proc3": {
      "process": "adding ingredients",
      "foodstuffsList": [
        "ing1",
        "proc2"
      ],
      "instruments": [
        {
          "instrument": "inst1",
          "usedAfter": false
        },
        {
          "instrument": "inst4",
          "usedAfter": true
        }
      ]
    },
    "proc4": {
      "process": "mixing",
      "foodstuff": "proc3",
      "instruments": [
        {
          "instrument": "inst4",
          "usedAfter": true
        }
      ]
    },
    "proc5": {
      "process": "adding ingredients",
      "foodstuffsList": [
        "proc4",
        "ing5",
        "ing6"
      ],
      "instruments": [
        {
          "instrument": "inst4",
          "usedAfter": true
        }
      ]
    },
    "proc6": {
      "process": "mixing",
      "foodstuff": "proc5",
      "instruments": [
        {
          "instrument": "inst4",
          "usedAfter": true
        }
      ]
    },
    "proc7": {
      "process": "kneading",
      "foodstuff": "proc6",
      "instruments": [
        {
          "instrument": "inst4",
          "usedAfter": false
        },
        {
          "instrument": "inst14",
          "usedAfter": true
        }
      ]
    },
    "proc8": {
      "process": "proofing",
      "parameters": {
        "endConditions": {
          "time": {
            "value": 25,
            "measure": "min"
          }
        }
      },
      "foodstuff": "proc7",
      "instruments": [
        {
          "instrument": "inst14",
          "usedAfter": false
        },
        {
          "instrument": "inst4",
          "usedAfter": true
        }
      ]
    },
    "proc9": {
      "process": "degassing",
      "foodstuff": "proc8",
      "instruments": [
        {
          "instrument": "inst4",
          "usedAfter": false
        },
        {
          "instrument": "inst14",
          "usedAfter": true
        }
      ]
    },
    "proc10": {
      "process": "dividing",
      "parameters": {
        "pieces": 1
      },
      "foodstuff": "proc9",
      "instruments": [
        {
          "instrument": "inst14",
          "usedAfter": true
        },
        {
          "instrument": "inst13",
          "usedAfter": false
        },
        {
          "instrument": "inst8",
          "usedAfter": false
        }
      ]
    },
    "proc11": {
      "process": "rounding",
      "foodstuff": "proc10",
      "instruments": [
        {
          "instrument": "inst14",
          "usedAfter": true
        }
      ]
    },
    "proc12": {
      "process": "proofing",
      "parameters": {
        "endConditions": {
          "time": {
            "value": 20,
            "measure": "min"
          }
        }
      },
      "foodstuff": "proc11",
      "instruments": [
        {
          "instrument": "inst14",
          "usedAfter": false
        },
        {
          "instrument": "inst4",
          "usedAfter": true
        }
      ]
    },
    "proc13": {
      "process": "degassing",
      "foodstuff": "proc12",
      "instruments": [
        {
          "instrument": "inst4",
          "usedAfter": false
        },
        {
          "instrument": "inst14",
          "usedAfter": true
        }
      ]
    },
    "proc14": {
      "process": "shaping",
      "foodstuff": "proc13",
      "instruments": [
        {
          "instrument": "inst14",
          "usedAfter": false
        },
        {
          "instrument": "inst9",
          "usedAfter": true
        }
      ]
    },
    "proc15": {
      "process": "proofing",
      "parameters": {
        "endConditions": {
          "time": {
            "value": 20,
            "measure": "min"
          }
        }
      },
      "foodstuff": "proc14",
      "instruments": [
        {
          "instrument": "inst9",
          "usedAfter": true
        }
      ]
    },
    "proc16": {
      "process": "chopping",
      "foodstuff": "ing8",
      "instruments": [
        {
          "instrument": "inst6",
          "usedAfter": true
        },
        {
          "instrument": "inst7",
          "usedAfter": false
        }
      ]
    },
    "proc17": {
      "process": "adding ingredients",
      "foodstuffsList": [
        "ing7",
        "proc16",
        "ing9",
        "ing10",
        "ing11"
      ],
      "instruments": [
        {
          "instrument": "inst6",
          "usedAfter": false
        },
        {
          "instrument": "inst4",
          "usedAfter": true
        }
      ]
    },
    "proc18": {
      "process": "mixing",
      "foodstuff": "proc17",
      "instruments": [
        {
          "instrument": "inst4",
